name: azstore
description: Flutter package to access azure storage options with easy to use functions. This package handles formatting of HTTPS requests to access azure REST APIs.
version: 1.0.0
homepage: https://github.com/Algure/azstore
repository: https://github.com/Algure/azstore.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.0
  http: ^0.13.0
  xml: ^5.1.0
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.4

flutter:
