name: azstore
description: Dart package to access azure storage options with easy to use functions. This package handles formatting of HTTPS requests to access azure REST APIs.
version: 1.1.0
homepage: https://github.com/Algure/azstore
repository: https://github.com/Algure/azstore.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  http: ^1.1.0
  xml: ^6.3.0
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^2.1.1
  mockito: ^5.4.2
  test: ^1.24.4
